### ISSUE TITLE
Support `autocompleteblocks`

### ISSUE THREAD

**Issue by georgms** [TheKeymaster/findologic-api#20]
[`autocompleteblocks`](https://docs.findologic.com/doku.php?id=smart_suggest_new) can be used to limit the number of requests autocomplete blocks. This parameter is currently not supported.

**Comment by TheKeymaster** [comment]
Thank you for this information @georgms. There is already an issue for supporting more request parameters and more response objects for the JsonResponse (see #19).  
This parameter (as well as others), will be added "soonish".
